import pyautogui as pya
import time
import datetime as dt
class scrappy():
    
    def get_the_url():
        global hj, name_file
        hj =  dt.date.today()
        # create a name for the file we will save
        name_file = 'fii_real_state_date'
        pya.hotkey('win')
        time.sleep(2)
        pya.write('brave',interval=0.2)
        time.sleep(2)
        pya.hotkey('enter')
        time.sleep(10)
        # get inside the url that we want scrappy
        pya.write('https://www.fundsexplorer.com.br/rendimentos-e-amortizacoes',interval=0.1)
        time.sleep(2)
        pya.hotkey('enter')
        time.sleep(10)
        pya.hotkey('esc')
        time.sleep(10)
        pya.hotkey('ctrl','a')
        time.sleep(2)
        pya.hotkey('ctrl','c')
        time.sleep(10)
    get_the_url()

    def extract_data_for_excel():
    # extract all the data in the webpage and paste inside the spreadsheet    
        pya.hotkey('win')
        time.sleep(5)
        pya.write('Excel',interval=0.1)
        time.sleep(1)
        pya.hotkey('enter')
        time.sleep(15)
        pya.hotkey('enter')
        time.sleep(3)
        pya.hotkey('ctrl','v')
        time.sleep(30)
        pya.hotkey('ctrl','b')
        time.sleep(4)
        pya.hotkey('tab')
        time.sleep(3)
        pya.hotkey('down')
        time.sleep(1)
        pya.hotkey('down')
        time.sleep(1)
        pya.hotkey('down')
        time.sleep(1)
        pya.hotkey('down')
        time.sleep(1)
        pya.hotkey('enter')
        time.sleep(10)
        pya.hotkey('ctrl','l')
        time.sleep(1)
        pya.write(r'C:\Users\guilherme.dias\Documents\GitHub\api-real_state_funds\databases',interval=0.1)
        time.sleep(1)
        pya.hotkey('enter')
        time.sleep(1)
        pya.hotkey('tab')
        time.sleep(1)
        pya.hotkey('tab')
        time.sleep(1)
        pya.hotkey('tab')
        time.sleep(1)
        pya.hotkey('tab')
        time.sleep(1)
        pya.hotkey('tab')
        time.sleep(1)
        pya.hotkey('tab')
        time.sleep(2)
        pya.write(f'{name_file}')
        time.sleep(2)
        pya.hotkey('tab')
        time.sleep(1)
        pya.hotkey('down')
        time.sleep(1)
        pya.hotkey('down')
        time.sleep(1)
        pya.hotkey('down')
        time.sleep(1)
        pya.hotkey('down')
        time.sleep(1)
        pya.hotkey('down')
        time.sleep(1)
        pya.hotkey('enter')
        time.sleep(3)
        pya.hotkey('enter')
        time.sleep(3)
        pya.hotkey('left')
        time.sleep(3)
        pya.hotkey('enter')
        time.sleep(45)
        pya.hotkey('alt','f4')
        time.sleep(5)
        pya.hotkey('enter')
        time.sleep(4)
        pya.hotkey('alt','f4')
        time.sleep(2)
    extract_data_for_excel()
scrappy()

print('########## COLETA FINALIZADA #############')
import os
path = r'C:\Users\guilherme.dias\Documents\GitHub\api-real_state_funds\databases'
list_of_files = os.listdir(path)
name_file_path = 'fii_real_state_date'
for name_file_path in list_of_files:
    print("File Saved with success inside the specified path.")


